### ISSUE TITLE
503 Error: Service Unavailable

### ISSUE THREAD

**Issue by detroyejr** [TractionOnDemand/TractionSyncProxy#21]
I've completed all the steps to setup the connector, but I hit a 503 error when exporting a sheet. It looks like the issue is coming from [format_list_data](https://github.com/TractionOnDemand/TractionSyncProxy/blob/master/server/salesforce/salesforce_utils.js#L114) when it tries to access the "length" method that, for whatever reason, doesn't exist.

I realize that it's difficult to debug from your end with only this much information, but if you have any insight that would be helpful. Others reviewing the extension experienced the same issue.

Here's the relevant log excerpt from heroku:

```
2018-01-09T21:59:37.372422+00:00 app[web.1]: format_list_data Exception: TypeError: Cannot read property 'length' of undefined
2018-01-09T21:59:37.374966+00:00 app[web.1]: /app/server/salesforce/salesforce_utils.js:44
2018-01-09T21:59:37.374979+00:00 app[web.1]:     at emitTwo (events.js:87:13)
2018-01-09T21:59:37.374970+00:00 app[web.1]:                                                              ^
2018-01-09T21:59:37.374968+00:00 app[web.1]:             for (var y = 0; y < req.sf_sync.list_data.columns.names.length; y++) {
2018-01-09T21:59:37.374978+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2018-01-09T21:59:37.374981+00:00 app[web.1]:     at emitOne (events.js:77:13)
2018-01-09T21:59:37.374984+00:00 app[web.1]:     at IncomingMessage.g (events.js:260:16)
2018-01-09T21:59:37.397644+00:00 app[web.1]: npm ERR! node v4.2.6
2018-01-09T21:59:37.374975+00:00 app[web.1]: TypeError: Cannot read property 'names' of undefined
2018-01-09T21:59:37.374980+00:00 app[web.1]:     at Request.emit (events.js:172:7)
2018-01-09T21:59:37.374982+00:00 app[web.1]:     at Request.emit (events.js:169:7)
```

Thanks for your work!

**Comment by detroyejr** [comment]
**Update:** Figured out how to debug a heroku app with vscode. 

One of the requests was returning a "403" error since API access was not enabled for our organization. Perhaps, the app could return an error message like it does for "401", but otherwise this issue is resolved.

**Comment by mark71j** [comment]
Oh, I have this issue! API access in G-Suite Admin?

**Comment by detroyejr** [comment]
API access in salesforce. The specific error message from salesforce was `API Access is not enabled for this Organization` with a 403 error code. It's one of the few error codes not handled by the api which is why you don't see the message without some digging.

Unfortunately, the solution isn't great. Per [this thread](https://success.salesforce.com/apex/answers?id=90630000000hxbhAAA), you'll need to call Salesforce customer support and add API access as a feature at a cost.

I was able to get the app to work when I setup a [developer account.](https://developer.salesforce.com/) Once setup, you can test the features and see if paying for the upgrade is worthwhile. The app successfully exported the test data to google sheets, but there were further problems with the google scripts (Google Web App step) that prevented syncing the data between accounts. Unfortunately, this issue is still unsolved.

Sorry I'm unable to help further!
